// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using nss.Models;

namespace nss.Migrations
{
    [DbContext(typeof(PoslasticaraContext))]
    [Migration("20210419202815_V6")]
    partial class V6
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("nss.Models.Narudzbina", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cena")
                        .HasColumnType("int")
                        .HasColumnName("cena");

                    b.Property<int>("Kolicina")
                        .HasColumnType("int")
                        .HasColumnName("kolicina");

                    b.Property<int?>("StoloveID")
                        .HasColumnType("int");

                    b.Property<string>("Vrsta")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("vrsta");

                    b.HasKey("ID");

                    b.HasIndex("StoloveID");

                    b.ToTable("Narudzbina");
                });

            modelBuilder.Entity("nss.Models.Poslasticara", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Kapacitet")
                        .HasColumnType("int")
                        .HasColumnName("Kapacitet");

                    b.Property<int>("M")
                        .HasColumnType("int")
                        .HasColumnName("M");

                    b.Property<int>("N")
                        .HasColumnType("int")
                        .HasColumnName("N");

                    b.Property<string>("Naziv")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Naziv");

                    b.HasKey("ID");

                    b.ToTable("Poslasticara");
                });

            modelBuilder.Entity("nss.Models.Stolovi", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImeRezervacije")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ImeRezervacije");

                    b.Property<int>("Kapacitet")
                        .HasColumnType("int")
                        .HasColumnName("Kapacitet");

                    b.Property<int>("MaxKapacitet")
                        .HasColumnType("int")
                        .HasColumnName("MaxKapacitet");

                    b.Property<int?>("PoslasticaraID")
                        .HasColumnType("int");

                    b.Property<string>("Pusac")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Pusac");

                    b.Property<int>("S")
                        .HasColumnType("int")
                        .HasColumnName("S");

                    b.HasKey("ID");

                    b.HasIndex("PoslasticaraID");

                    b.ToTable("Stolovi");
                });

            modelBuilder.Entity("nss.Models.Narudzbina", b =>
                {
                    b.HasOne("nss.Models.Stolovi", "Stolove")
                        .WithMany("Narudzbinaa")
                        .HasForeignKey("StoloveID");

                    b.Navigation("Stolove");
                });

            modelBuilder.Entity("nss.Models.Stolovi", b =>
                {
                    b.HasOne("nss.Models.Poslasticara", "Poslasticara")
                        .WithMany("Stolovii")
                        .HasForeignKey("PoslasticaraID");

                    b.Navigation("Poslasticara");
                });

            modelBuilder.Entity("nss.Models.Poslasticara", b =>
                {
                    b.Navigation("Stolovii");
                });

            modelBuilder.Entity("nss.Models.Stolovi", b =>
                {
                    b.Navigation("Narudzbinaa");
                });
#pragma warning restore 612, 618
        }
    }
}
